/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Event {
  'id' : EventId,
  'title' : string,
  'description' : string,
  'end_time' : string,
  'start_time' : string,
  'location' : string,
}
export type EventId = bigint;
export interface ProgrammeOverview {
  'last_updated' : string,
  'events' : Array<Event>,
}
export interface _SERVICE {
  'addEvent' : ActorMethod<[string, string, string, string, string], EventId>,
  'deleteEvent' : ActorMethod<[EventId], undefined>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getEvent' : ActorMethod<[EventId], [] | [Event]>,
  'getProgrammeOverview' : ActorMethod<[], ProgrammeOverview>,
  'updateEvent' : ActorMethod<
    [EventId, string, string, string, string, string],
    undefined
  >,
  'updateProgrammeOverview' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];